### ISSUE TITLE
Differential Residual Ratio Tracking

### ISSUE THREAD

**Issue by andyyankai** [rgl-epfl/unbiased-inverse-volume-rendering#5]
Hi Merlin,
Is Differential Residual Ratio Tracking used in this code base?
I only see ratio tracking I think. Do you think it is easy to add Ratio Tracking or Residual Ratio Tracking on lastest mitsuba3? (i noticed you already implemented it in your project branch for mitsuba3
Thanks!

**Comment by merlinND** [comment]
Hello @andyyankai,

I believe that Differential Residual Ratio Tracking was not included in the main release Integrator because it did not significantly improve variance in our tests. However, the pseudocode is included in the paper (appendix B + listing 2) and the sampling method is implemented on the Mitsuba side ([`Medium::sample_interaction_drrt()`](https://github.com/mitsuba-renderer/mitsuba3/blob/unbiased-inverse-volume-rendering/src/render/medium.cpp#L348-L422)).

In terms of updating the codebase to the latest Mitsuba 3 version, some of the following changes would need to be rebased : https://github.com/mitsuba-renderer/mitsuba3/compare/4b428a03ed4502725f1fca46499a136fbd9d8a95...unbiased-inverse-volume-rendering
Note that some of these changes are just performance optimizations that could be omitted, or might have been implemented in the newest version already.

The volumetric path tracer should also be updated: https://github.com/rgl-epfl/unbiased-inverse-volume-rendering/blob/c80b375deca3197f89cdde3bc46b1630c4142c19/python/integrators/volpathsimple.py
However, as a Python-based plugin, it should be relatively easy.

**Comment by andyyankai** [comment]
Thanks for the help!
